name: Build and Release

on:
  push:
    branches: [ main, master ]  # 每次推送到主分支时触发
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write  # 需要写权限来创建release和上传文件

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'
        
    - name: Run tests
      run: make test
      
    - name: Build binary
      run: make build
      
    - name: Create release directory
      run: mkdir -p release
      
    - name: Copy binary to release directory
      run: cp next-starter release/next-starter-linux-amd64
      
    - name: Get commit info
      id: commit
      run: |
        echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        echo "commit_msg=$(git log -1 --pretty=%B | head -1)" >> $GITHUB_OUTPUT
        echo "build_date=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT
        
    - name: Generate release notes
      run: |
        echo "## Auto Build - ${{ steps.commit.outputs.build_date }}" > release-notes.md
        echo "" >> release-notes.md
        echo "**Commit:** ${{ steps.commit.outputs.short_sha }}" >> release-notes.md
        echo "**Message:** ${{ steps.commit.outputs.commit_msg }}" >> release-notes.md
        echo "" >> release-notes.md
        echo "## Usage" >> release-notes.md
        echo "\`\`\`bash" >> release-notes.md
        echo "# Download and make executable" >> release-notes.md
        echo "chmod +x next-starter-linux-amd64" >> release-notes.md
        echo "" >> release-notes.md
        echo "# Use the tool" >> release-notes.md
        echo "./next-starter-linux-amd64 my-project-name" >> release-notes.md
        echo "\`\`\`" >> release-notes.md
      
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: "build-${{ steps.commit.outputs.short_sha }}"
        name: "Auto Build - ${{ steps.commit.outputs.short_sha }}"
        files: release/next-starter-linux-amd64
        body_path: release-notes.md
        draft: false
        prerelease: true  # 标记为预发布版本
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: next-starter-linux-amd64
        path: release/next-starter-linux-amd64
        retention-days: 30
        compression-level: 6